### ISSUE TITLE
stretch goal

### ISSUE THREAD

**Issue by orangepaydev** [tyl1999tyl/RecordSimilarity#3]
As a stretch goal, see if you could implement the code you have in kotlin.  You'll discover how simple your code will look.

e.g. it'll look something like this:

    val recordList = mutableListOf<String>()
    val dataList = File("path").bufferedReader().forEachLine {
        recordList.add(Recrd(it))
    }
    recordList.forEach {record1 ->
        recordList.forEach { record2 ->
            ....
        }
    }

**Comment by tyl1999tyl** [comment]
Converted one class over here: https://github.com/tyl1999tyl/RecordSimilarity/commit/461474e95f322545531821d8e5bc105f9305677f
