### ISSUE TITLE
Possible out f file handler issue

### ISSUE THREAD

**Issue by orangepaydev** [tyl1999tyl/RecordSimilarity#4]
https://github.com/tyl1999tyl/RecordSimilarity/blob/de7c4a1e8ecb16b39bdefe52376b3e575810ffe6/src/main/java/com/tyl/recordsimilarity/util/RecordFileUtil.java#L22

if this code is executed a million times....will it eventually run out of file handler?

**Comment by tyl1999tyl** [comment]
I'm using try-with-resources statement here, where it will close the file handler once the code is executed, so it shouldn't be a case where file handler is ran out.
